### ISSUE TITLE
Is the `jumpMarkersEnabled` page property evaluated?

### ISSUE THREAD

**Issue by alexander-nitsche** [code-q-web-factory/CodeQ.JumpMarkers#4]
Is the page property `jumpMarkersEnabled` in NodeTypes.Mixin.PageConfiguration.yaml evaluated by some convention-over-configuration magic, or is it deprecated? I can find only one occurence of this keyword which is in NodeTypes.Mixin.PageConfiguration.yaml.

**Comment by rolandschuetz** [comment]
Yes, you're right. I fixed it and write the necessary information into the readme.
