### ISSUE TITLE
Neos UI Error "None of the given schemas null,dictionary matched array"

### ISSUE THREAD

**Issue by alexander-nitsche** [code-q-web-factory/CodeQ.JumpMarkers#5]
After installing this package in a Neos 7 LTS instance, the error "None of the given schemas null,dictionary matched array" is displayed when navigating to Administration > Configuration and going to the "NodeTypes" tab. See screenshot:

![codeq-jumpmarkers-neos-ui-configuration-error](https://user-images.githubusercontent.com/20297232/231996884-7d477edc-7656-4808-a3b0-f00cc42a12b6.png)

**Comment by rolandschuetz** [comment]
Weird, not really sure how this works, the relevant code is here.
https://github.com/code-q-web-factory/CodeQ.JumpMarkers/blob/master/Configuration/NodeTypes.Mixin.SectionConfiguration.yaml#L16

**Comment by alexander-nitsche** [comment]
The same error pops up when running 
```
flow configuration:validate
```
on CLI and is urged by 
```
position: 'before sectionId'
```
of the jumpMarkerTitle property definition, which should be of type integer or null (according to the [Neos Node Type Schema](https://github.com/neos/neos-development-collection/blob/7.3/Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml#L59)).

As it does not validate, the error bubbles and urges all parent configurations to fail too, ending with the whole jumpMarkerTitle property not being a valid dictionary.

**Comment by rolandschuetz** [comment]
A bit weird, but easy to fix. Thanks for the hint!

**Comment by alexander-nitsche** [comment]
The new positions caused moving the copy buttons to the top, which is probably unwanted.
![codeq-jumpmarkers-positioning](https://user-images.githubusercontent.com/20297232/232297226-d9055c3e-73d7-4257-b766-1c6f8a8829a0.png)

**Comment by rolandschuetz** [comment]
Ah, sorry for not properly testing. Now it works
