### ISSUE TITLE
Copy buttons stick together for long labels

### ISSUE THREAD

**Issue by alexander-nitsche** [code-q-web-factory/CodeQ.JumpMarkers#6]
The copy buttons stick together for long labels and could maybe do with a minimum distance. For example in German it looks like:
![codeq-jumpmarkers-buttons-stick-together](https://user-images.githubusercontent.com/20297232/232321897-5c457379-0b30-422f-ba4a-fe12a278d6a1.png)

**Comment by rolandschuetz** [comment]
Yeah, I agree. Currently I spend my unpaid hours working on NEOSidekick though 🤷‍♂️

**Comment by alexander-nitsche** [comment]
Ok, how are the public JS and CSS resources of the package compiled?

**Comment by alexander-nitsche** [comment]
For example, replacing 
```
display: 'flex',
justifyContent: 'space-between
```
with
```
display: 'flex',
flexDirection: 'column',
gap: '8px 0px'
```
would be aligned with similar buttons in Neos modules (8px margin), and provide enough space for large labels:

![codeq-jumpmarkers-buttons-relaxed](https://user-images.githubusercontent.com/20297232/232415153-ed516bc8-f4be-4d39-9dc7-7e152411cb1f.png)

**Comment by rolandschuetz** [comment]
Currently here's only inline CSS:
https://github.com/code-q-web-factory/CodeQ.JumpMarkers/blob/master/Resources/Public/JavaScript/Inspector/Views/AnchorView.html

**Comment by alexander-nitsche** [comment]
Searching for label "Kopiere Neos-Link" returns properties.sectionId.copy-neos-link label. And searching for this label returns 

1. Resources/Private/JavaScript/AnchorView/src/AnchorView.js
2. Resources/Private/Translations/de/NodeTypes/Mixin/SectionConfiguration.xlf
3. Resources/Private/Translations/en/NodeTypes/Mixin/SectionConfiguration.xlf
4. Resources/Public/JavaScript/AnchorView/Plugin.js
5. Resources/Public/JavaScript/AnchorView/Plugin.js.map

where (4) and (5) seem to be compiled from (1), not?

**Comment by rolandschuetz** [comment]
yes, see:
https://github.com/code-q-web-factory/CodeQ.JumpMarkers/tree/master/Resources/Private/JavaScript/AnchorView#how-to-build-the-frontend
