### ISSUE TITLE
Error 401 when trying to Copy Link

### ISSUE THREAD

**Issue by paavo** [code-q-web-factory/CodeQ.JumpMarkers#8]
When i try to copy the Link (Neos Link works well) i get an error:
401 can't access /neos/jump-markers-node-to-uri/...

```
The security context contained no tokens which could be authenticated.

Evaluated following 1 privilege target(s):
"Neos.Neos:Backend.OtherUsersPersonalWorkspaceAccess": ABSTAIN
(0 granted, 0 denied, 1 abstained)
```

Any idea what could be wrong? 🤔

**Comment by rolandschuetz** [comment]
After you installed the package, you need to log out and in once, or destroy all sessions since we introduced a new priviledge for this. 

Did this help fixing your issue?
